CREATE TABLE stories (
  id INT64,
  name STRING(MAX),
  serving_size STRING(MAX),
  calories STRING(MAX),
  total_fat STRING(MAX),
  carbohydrate STRING(MAX),
  fiber STRING(MAX),
  sugars STRING(MAX),
  glucose STRING(MAX),
  lactose STRING(MAX),
  fat STRING(MAX),
  ash STRING(MAX),
  caffeine STRING(MAX),
  water STRING(MAX),
) PRIMARY KEY(id);
